### ISSUE TITLE
Online updating with MALLET

### ISSUE THREAD

**Issue by Pranav-Goel** [maria-antoniak/little-mallet-wrapper#11]
Hi Maria,

Thanks for this wrapper for MALLET - it is great to have a viable alternative to Gensim! Is there any way online updating can be done with this wrapper so that the model can resume training when new documents come in? In other words, can the wrapped model be updated with new documents for online training? From what I understand, Gensim LDA (not the MALLET wrapper) can support that but Gensim LDA is demonstrably and clearly worse than MALLET, and it would be great to have the online training/updating functionality with MALLET. 

Thanks!

**Comment by maria-antoniak** [comment]
Hi Pranav! Unfortunately no, you can't do online updating because MALLET uses Gibbs sampling for training (which is also the source of the better output compared to Gensim). You can infer topics on new documents, but you can't add new documents into the training. I think there are online learning versions of Gibbs sampling (see links below, I found them via a quick search but haven't read), but to my knowledge, they aren't implemented in MALLET. You might also like to try out [tomotopy](https://bab2min.github.io/tomotopy/v0.12.2/en/), which has more more kinds of models available.

https://arxiv.org/abs/1601.01142
https://proceedings.mlr.press/v5/canini09a

**Comment by Pranav-Goel** [comment]
That makes sense, thank you so much!
